### ISSUE TITLE
CMake configure_package is missing DEPENDENCIES.

### ISSUE THREAD

**Issue by Levi-Armstrong** [marip8/plugin_loader#8]
For the find package config to be generated correctly it need to add the list of dependencies [here](https://github.com/marip8/plugin_loader/blob/fd4a46aab56cd363d7c6b86deb3507b2c7a5c8d3/CMakeLists.txt#L32)

``` cmake
configure_package(
NAMESPACE ${PROJECT_NAME} 
DEPENDENCIES "Boost REQUIRED COMPONENTS filesystem"
TARGETS ${PROJECT_NAME})
```

**Comment by marip8** [comment]
Good find. I think I'm missing this in a few other repositories as well. For reference, how do you add dependencies on multiple projects? Like this?
```cmake
configure_package(
NAMESPACE ${PROJECT_NAME} 
DEPENDENCIES
  "Boost REQUIRED COMPONENTS filesystem"
  "PCL REQUIRED COMPONENTS common io"
TARGETS ${PROJECT_NAME})
```

**Comment by marip8** [comment]
Closing; addressed in #9

**Comment by Levi-Armstrong** [comment]
> Good find. I think I'm missing this in a few other repositories as well. For reference, how do you add dependencies on multiple projects? Like this?
> 
> ```cmake
> configure_package(
> NAMESPACE ${PROJECT_NAME} 
> DEPENDENCIES
>   "Boost REQUIRED COMPONENTS filesystem"
>   "PCL REQUIRED COMPONENTS common io"
> TARGETS ${PROJECT_NAME})
> ```

Yep, Now only things using components need to be wrapped in double quotes everything else can just be listed. The configure_packge also support a [CFG_CONFIG](https://github.com/tesseract-robotics/tesseract_qt/blob/2673aebc56b1b355a28d638b66125e87ebb34ab2/CMakeLists.txt#L31-L48) like what is shown here for extra things.

 ```cmake
 configure_package(
 NAMESPACE ${PROJECT_NAME} 
 DEPENDENCIES
   "Boost REQUIRED COMPONENTS filesystem"
   "PCL REQUIRED COMPONENTS common io"
   tesseract_common
   tesseract_collision
 TARGETS ${PROJECT_NAME})
 ```

**Comment by Levi-Armstrong** [comment]
https://github.com/ros-industrial/ros_industrial_cmake_boilerplate#configure-pure-cmake-package
